"""The nomissuccess logo band as a Geometry-Nodes ribbon.

``build(path_points, width, thickness)`` creates a polyline mesh carrying
per-point attributes and a ``NomissBand`` Geometry-Nodes modifier that turns
it into a real 3D band:

* stadium cross-section (``width`` x ``thickness``, fully rounded edges),
* colour coordinate ``u`` (0..1 along the band) for the colour ramp,
* ``kante`` (1 on the long edges) and ``kopf`` (1 at the growth head) for the
  emissive edge / head in :func:`nomiss_material.ribbon_material`,
* growth along the path via the inputs ``Start``/``Ende`` (trim factors),
  with a soft tapering tail (``Schweif Laenge``) and a hot head (``Kopf Laenge``),
* an optional twist (``Drall`` turns along the band length, ``Drall Phase``),
* a morph from a helix (``Spirale ...`` inputs) into the stored pose with a
  staggered smootherstep (``Morph`` 0..1, ``Staffelung``).  At ``Morph = 1``
  every point is exactly in its stored pose, with zero velocity.

Stored per-point attributes on the polyline:
``u`` (float), ``drall_ziel`` (twist, rad), ``skala_ziel`` (profile scale) and ``nrm``
(thickness direction before tilt).

:func:`build_logo` builds the "N" from ``blender/assets/logo_band.json``
(generated by ``nomiss_logo.py``) in the world XZ plane, facing -Y.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import bpy
import numpy as np

REPO = Path(__file__).resolve().parents[2]
LOGO_BAND_JSON = REPO / "blender" / "assets" / "logo_band.json"
GROUP = "NomissBand"
MOD = "NomissBand"
TAU = 2.0 * math.pi


# --------------------------------------------------------------------------
# tiny node-graph builder
# --------------------------------------------------------------------------

class _B:
    def __init__(self, tree: bpy.types.NodeTree):
        self.t = tree

    def node(self, typ: str, **props):
        n = self.t.nodes.new(typ)
        for k, v in props.items():
            setattr(n, k, v)
        return n

    def put(self, sock, v):
        if isinstance(v, bpy.types.NodeSocket):
            self.t.links.new(v, sock)
        elif v is not None:
            sock.default_value = v

    def math(self, op, a, b=None, c=None, clamp=False):
        n = self.node("ShaderNodeMath", operation=op, use_clamp=clamp)
        for i, v in enumerate((a, b, c)):
            if v is not None:
                self.put(n.inputs[i], v)
        return n.outputs[0]

    def vmath(self, op, a, b=None, scale=None):
        n = self.node("ShaderNodeVectorMath", operation=op)
        self.put(n.inputs[0], a)
        if b is not None:
            self.put(n.inputs[1], b)
        if scale is not None:
            self.put(n.inputs["Scale"], scale)
        return n.outputs["Value"] if op in ("DOT_PRODUCT", "LENGTH", "DISTANCE") else n.outputs["Vector"]

    def vec(self, x, y, z):
        n = self.node("ShaderNodeCombineXYZ")
        for i, v in enumerate((x, y, z)):
            self.put(n.inputs[i], v)
        return n.outputs[0]

    def attr(self, name: str, dtype: str = "FLOAT"):
        n = self.node("GeometryNodeInputNamedAttribute", data_type=dtype)
        n.inputs["Name"].default_value = name
        return n.outputs["Attribute"]

    def lerp(self, a, b, f):
        return self.math("ADD", a, self.math("MULTIPLY", self.math("SUBTRACT", b, a), f))

    def vlerp(self, a, b, f):
        return self.vmath("ADD", a, self.vmath("SCALE", self.vmath("SUBTRACT", b, a), scale=f))

    def rotate_euler(self, v, euler):
        n = self.node("ShaderNodeVectorRotate", rotation_type="EULER_XYZ")
        self.put(n.inputs["Vector"], v)
        self.put(n.inputs["Rotation"], euler)
        return n.outputs[0]


def _menu(sock, label: str) -> None:
    sock.default_value = label
    if sock.default_value != label:
        raise RuntimeError(f"Menü-Wert '{label}' nicht gesetzt ({sock.node.bl_idname}.{sock.name})")


# --------------------------------------------------------------------------
# the node group
# --------------------------------------------------------------------------

INPUTS: list[tuple[str, str, object, float | None, float | None]] = [
    ("Breite", "NodeSocketFloat", 0.1, 0.0, None),
    ("Dicke", "NodeSocketFloat", 0.02, 0.0, None),
    ("Start", "NodeSocketFloat", 0.0, 0.0, 1.0),
    ("Ende", "NodeSocketFloat", 1.0, 0.0, 1.0),
    ("Kopf Laenge", "NodeSocketFloat", 0.0, 0.0, None),
    ("Schweif Laenge", "NodeSocketFloat", 0.0, 0.0, None),
    ("Drall", "NodeSocketFloat", 0.0, None, None),
    ("Drall Phase", "NodeSocketFloat", 0.0, None, None),
    ("Morph", "NodeSocketFloat", 1.0, 0.0, 1.0),
    ("Staffelung", "NodeSocketFloat", 0.0, 0.0, 0.95),
    ("Spirale Mitte", "NodeSocketVector", (0.0, 0.0, 0.0), None, None),
    ("Spirale Drehung", "NodeSocketVector", (0.0, 0.0, 0.0), None, None),
    ("Spirale Radius", "NodeSocketFloat", 1.0, None, None),
    ("Spirale Windungen", "NodeSocketFloat", 2.0, None, None),
    ("Spirale Laenge", "NodeSocketFloat", 2.0, None, None),
    ("Spirale Phase", "NodeSocketFloat", 0.0, None, None),
    ("Spirale Konus", "NodeSocketFloat", 0.0, None, None),
    ("Spirale Drall", "NodeSocketFloat", 0.0, None, None),
    ("Spirale Skala", "NodeSocketFloat", 1.0, 0.0, None),
]


def band_group() -> bpy.types.NodeTree:
    ng = bpy.data.node_groups.get(GROUP)
    if ng is not None:
        return ng
    ng = bpy.data.node_groups.new(GROUP, "GeometryNodeTree")
    ng.interface.new_socket(name="Geometry", in_out="INPUT", socket_type="NodeSocketGeometry")
    ng.interface.new_socket(name="Geometry", in_out="OUTPUT", socket_type="NodeSocketGeometry")
    for name, typ, default, mn, mx in INPUTS:
        s = ng.interface.new_socket(name=name, in_out="INPUT", socket_type=typ)
        if default is not None:
            s.default_value = default
        if mn is not None:
            s.min_value = mn
        if mx is not None:
            s.max_value = mx

    b = _B(ng)
    gi = b.node("NodeGroupInput")
    go = b.node("NodeGroupOutput")

    def I(name):
        return gi.outputs[name]

    m2c = b.node("GeometryNodeMeshToCurve")
    b.put(m2c.inputs["Mesh"], I("Geometry"))

    u = b.attr("u")

    # ---- staggered smootherstep morph factor e(u) --------------------------
    stag = I("Staffelung")
    num = b.math("SUBTRACT", I("Morph"), b.math("MULTIPLY", stag, u))
    den = b.math("MAXIMUM", b.math("SUBTRACT", 1.0, stag), 1e-4)
    m = b.math("DIVIDE", num, den, clamp=True)
    mr = b.node("ShaderNodeMapRange", interpolation_type="SMOOTHERSTEP")
    b.put(mr.inputs["Value"], m)
    e = mr.outputs["Result"]

    # ---- helix source pose -------------------------------------------------
    theta = b.math("ADD", I("Spirale Phase"), b.math("MULTIPLY", I("Spirale Windungen"), b.math("MULTIPLY", u, TAU)))
    rr = b.math("MULTIPLY", I("Spirale Radius"), b.math("ADD", 1.0, b.math("MULTIPLY", I("Spirale Konus"), b.math("SUBTRACT", u, 0.5))))
    local = b.vec(
        b.math("MULTIPLY", rr, b.math("COSINE", theta)),
        b.math("MULTIPLY", I("Spirale Laenge"), b.math("SUBTRACT", u, 0.5)),
        b.math("MULTIPLY", rr, b.math("SINE", theta)),
    )
    helix = b.vmath("ADD", b.rotate_euler(local, I("Spirale Drehung")), I("Spirale Mitte"))
    posn = b.node("GeometryNodeInputPosition").outputs[0]
    pos = b.vlerp(helix, posn, e)
    setpos = b.node("GeometryNodeSetPosition")
    b.put(setpos.inputs["Geometry"], m2c.outputs["Curve"])
    b.put(setpos.inputs["Position"], pos)

    # ---- thickness direction with twist ------------------------------------
    n_tgt = b.attr("nrm", "FLOAT_VECTOR")
    n_hel = b.rotate_euler((0.0, -1.0, 0.0), I("Spirale Drehung"))
    n_mix = b.vlerp(n_hel, n_tgt, e)
    tan = b.node("GeometryNodeInputTangent").outputs[0]
    n_orth = b.vmath("NORMALIZE", b.vmath("SUBTRACT", n_mix, b.vmath("SCALE", tan, scale=b.vmath("DOT_PRODUCT", n_mix, tan))))
    tilt_hel = b.math("ADD", b.math("MULTIPLY", I("Spirale Drall"), b.math("MULTIPLY", u, TAU)), b.math("MULTIPLY", I("Spirale Phase"), 0.5))
    tilt = b.lerp(tilt_hel, b.attr("drall_ziel"), e)
    # extra twist along the band by length fraction (not by colour u)
    len_fac = b.node("GeometryNodeSplineParameter").outputs["Factor"]
    tilt = b.math("ADD", tilt, b.math("ADD", b.math("MULTIPLY", I("Drall"), b.math("MULTIPLY", len_fac, TAU)), I("Drall Phase")))
    binorm = b.vmath("CROSS_PRODUCT", tan, n_orth)
    n_fin = b.vmath(
        "ADD",
        b.vmath("SCALE", n_orth, scale=b.math("COSINE", tilt)),
        b.vmath("SCALE", binorm, scale=b.math("SINE", tilt)),
    )
    setn = b.node("GeometryNodeSetCurveNormal")
    b.put(setn.inputs["Curve"], setpos.outputs["Geometry"])
    _menu(setn.inputs["Mode"], "Free")
    b.put(setn.inputs["Normal"], n_fin)

    # ---- hot head (by length fraction, independent of the colour u) -------
    fac = b.node("GeometryNodeSplineParameter").outputs["Factor"]
    gap = b.math("SUBTRACT", I("Ende"), fac)
    kopf = b.math("SUBTRACT", 1.0, b.math("DIVIDE", gap, b.math("MAXIMUM", I("Kopf Laenge"), 1e-5)), clamp=True)
    kopf = b.math("MULTIPLY", kopf, b.math("GREATER_THAN", I("Kopf Laenge"), 0.0))
    st_kopf = b.node("GeometryNodeStoreNamedAttribute", data_type="FLOAT", domain="POINT")
    st_kopf.inputs["Name"].default_value = "kopf"
    b.put(st_kopf.inputs["Geometry"], setn.outputs["Curve"])
    b.put(st_kopf.inputs["Value"], kopf)

    # ---- soft tail: profile tapers to 0 over "Schweif Laenge" after Start --
    tail = b.math("DIVIDE", b.math("SUBTRACT", fac, I("Start")), b.math("MAXIMUM", I("Schweif Laenge"), 1e-6), clamp=True)
    tail_on = b.math("GREATER_THAN", I("Schweif Laenge"), 0.0)
    tail = b.math("ADD", b.math("MULTIPLY", tail, tail_on), b.math("SUBTRACT", 1.0, tail_on))
    tmr = b.node("ShaderNodeMapRange", interpolation_type="SMOOTHSTEP")
    b.put(tmr.inputs["Value"], tail)
    st_tail = b.node("GeometryNodeStoreNamedAttribute", data_type="FLOAT", domain="POINT")
    st_tail.inputs["Name"].default_value = "schweif"
    b.put(st_tail.inputs["Geometry"], st_kopf.outputs["Geometry"])
    b.put(st_tail.inputs["Value"], tmr.outputs["Result"])

    # ---- growth along the path (trim by length fraction) ------------------
    trim = b.node("GeometryNodeTrimCurve", mode="FACTOR")
    b.put(trim.inputs["Curve"], st_tail.outputs["Geometry"])
    b.put(trim.inputs["Start"], I("Start"))
    b.put(trim.inputs["End"], I("Ende"))

    # ---- stadium profile ----------------------------------------------------
    quad = b.node("GeometryNodeCurvePrimitiveQuadrilateral", mode="RECTANGLE")
    # profile X follows the curve normal (thickness), profile Y spans the width
    b.put(quad.inputs["Width"], I("Dicke"))
    b.put(quad.inputs["Height"], I("Breite"))
    fil = b.node("GeometryNodeFilletCurve")
    b.put(fil.inputs["Curve"], quad.outputs["Curve"])
    b.put(fil.inputs["Radius"], b.math("MULTIPLY", I("Dicke"), 0.5))
    fil.inputs["Limit Radius"].default_value = True
    _menu(fil.inputs["Mode"], "Poly")
    fil.inputs["Count"].default_value = 6
    sep = b.node("ShaderNodeSeparateXYZ")
    b.put(sep.inputs[0], b.node("GeometryNodeInputPosition").outputs[0])
    kante = b.math("DIVIDE", b.math("ABSOLUTE", sep.outputs["Y"]), b.math("MAXIMUM", b.math("MULTIPLY", I("Breite"), 0.5), 1e-6))
    st_kante = b.node("GeometryNodeStoreNamedAttribute", data_type="FLOAT", domain="POINT")
    st_kante.inputs["Name"].default_value = "kante"
    b.put(st_kante.inputs["Geometry"], fil.outputs["Curve"])
    b.put(st_kante.inputs["Value"], kante)

    # ---- sweep -------------------------------------------------------------
    scale = b.math("MULTIPLY", b.lerp(I("Spirale Skala"), b.attr("skala_ziel"), e), b.attr("schweif"))
    c2m = b.node("GeometryNodeCurveToMesh")
    b.put(c2m.inputs["Curve"], trim.outputs["Curve"])
    b.put(c2m.inputs["Profile Curve"], st_kante.outputs["Geometry"])
    b.put(c2m.inputs["Scale"], scale)
    c2m.inputs["Fill Caps"].default_value = True
    smooth = b.node("GeometryNodeSetShadeSmooth")
    b.put(smooth.inputs[0], c2m.outputs["Mesh"])
    smooth.inputs["Shade Smooth"].default_value = True
    # The material comes from the object's slot 0.  (Passing a material
    # through a modifier input hangs EEVEE renders in Blender 5.2.1.)
    b.put(go.inputs[0], smooth.outputs[0])
    return ng


# --------------------------------------------------------------------------
# object construction
# --------------------------------------------------------------------------

def arc_param(points: np.ndarray) -> np.ndarray:
    s = np.concatenate([[0.0], np.cumsum(np.linalg.norm(np.diff(points, axis=0), axis=1))])
    return s / max(s[-1], 1e-12)


def transport_normals(points: np.ndarray, up=(0.0, 0.0, 1.0)) -> np.ndarray:
    """Rotation-minimising normals (parallel transport) along a polyline."""
    p = np.asarray(points, dtype=np.float64)
    t = np.gradient(p, axis=0)
    t /= np.maximum(np.linalg.norm(t, axis=1, keepdims=True), 1e-12)
    n = np.zeros_like(p)
    up = np.asarray(up, dtype=np.float64)
    n0 = up - t[0] * np.dot(up, t[0])
    if np.linalg.norm(n0) < 1e-6:
        n0 = np.cross(t[0], [1.0, 0.0, 0.0])
    n[0] = n0 / np.linalg.norm(n0)
    for i in range(1, len(p)):
        v = n[i - 1] - t[i] * np.dot(n[i - 1], t[i])
        ln = np.linalg.norm(v)
        n[i] = v / ln if ln > 1e-9 else n[i - 1]
    return n


def build(
    path_points,
    width: float,
    thickness: float,
    *,
    name: str = "Band",
    material: bpy.types.Material | None = None,
    tilt=None,
    radius=None,
    normals=None,
    u=None,
    collection: bpy.types.Collection | None = None,
) -> bpy.types.Object:
    """Create the band object; returns it with the ``NomissBand`` modifier."""
    p = np.asarray(path_points, dtype=np.float64)
    n = len(p)
    u = arc_param(p) if u is None else np.asarray(u, dtype=np.float64)
    tilt = np.zeros(n) if tilt is None else np.asarray(tilt, dtype=np.float64)
    radius = np.ones(n) if radius is None else np.asarray(radius, dtype=np.float64)
    normals = transport_normals(p) if normals is None else np.asarray(normals, dtype=np.float64)

    me = bpy.data.meshes.new(name)
    me.from_pydata(p.tolist(), [(i, i + 1) for i in range(n - 1)], [])
    for aname, data in (("u", u), ("drall_ziel", tilt), ("skala_ziel", radius)):
        a = me.attributes.new(aname, "FLOAT", "POINT")
        a.data.foreach_set("value", data.astype(np.float32))
    a = me.attributes.new("nrm", "FLOAT_VECTOR", "POINT")
    a.data.foreach_set("vector", normals.astype(np.float32).ravel())

    ob = bpy.data.objects.new(name, me)
    (collection or bpy.context.scene.collection).objects.link(ob)
    mod = ob.modifiers.new(MOD, "NODES")
    mod.node_group = band_group()
    set_input(ob, "Breite", float(width))
    set_input(ob, "Dicke", float(thickness))
    if material is not None:
        from nomiss_material import assign

        assign(ob, material)
    return ob


def _ident(ob: bpy.types.Object, name: str) -> str:
    for item in ob.modifiers[MOD].node_group.interface.items_tree:
        if getattr(item, "in_out", None) == "INPUT" and item.name == name:
            return item.identifier
    raise KeyError(f"Band-Eingang '{name}' fehlt")


def _is_v5(mod) -> bool:
    props = getattr(mod, "properties", None)
    return props is not None and hasattr(props, "inputs")


def input_path(ob: bpy.types.Object, name: str, mod_name: str = MOD) -> str:
    """Animation data path of a modifier input (Blender 5.x and 4.x)."""
    ident = _ident(ob, name)
    if _is_v5(ob.modifiers[mod_name]):
        # 5.x: each input is an ID-property group {value, type, attribute_name}
        return f'modifiers["{mod_name}"].properties.inputs["{ident}"]["value"]'
    return f'modifiers["{mod_name}"]["{ident}"]'


def set_input(ob: bpy.types.Object, name: str, value) -> None:
    mod = ob.modifiers[MOD]
    ident = _ident(ob, name)
    if _is_v5(mod):
        mod.properties.inputs[ident]["value"] = tuple(value) if isinstance(value, (tuple, list)) else value
    else:
        mod[ident] = value


def get_input(ob: bpy.types.Object, name: str):
    mod = ob.modifiers[MOD]
    ident = _ident(ob, name)
    v = mod.properties.inputs[ident]["value"] if _is_v5(mod) else mod[ident]
    try:
        return tuple(v)
    except TypeError:
        return v


def key_input(ob: bpy.types.Object, name: str, frame: float, value, *, interp: str = "BEZIER", easing: str = "AUTO") -> None:
    from nomiss_camera import set_key_interp

    set_input(ob, name, value)
    path = input_path(ob, name)
    ob.keyframe_insert(path, frame=frame)
    set_key_interp(ob, path, frame, interp, easing)


def bake_input(ob: bpy.types.Object, name: str, frames, fn) -> None:
    """Per-frame keys from ``fn(frame) -> value`` (linear in between)."""
    from nomiss_camera import set_key_interp

    path = input_path(ob, name)
    for f in frames:
        set_input(ob, name, fn(f))
        ob.keyframe_insert(path, frame=f)
    for f in frames:
        set_key_interp(ob, path, f, "LINEAR", "AUTO")


# --------------------------------------------------------------------------
# the logo "N"
# --------------------------------------------------------------------------

def logo_data(path: Path = LOGO_BAND_JSON) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def logo_points(height: float, data: dict | None = None):
    """World-space pose of the N (XZ plane, facing -Y), centred on 0."""
    d = data or logo_data()
    k = height / d["logo_px"][1]
    cx, cy = d["zentrum_px"]
    f = d["felder"]
    arr = np.asarray(d["punkte"], dtype=np.float64)
    col = {name: arr[:, i] for i, name in enumerate(f)}
    pts = np.stack([(col["x"] - cx) * k, col["z"] * k, (cy - col["y"]) * k], axis=1)
    return pts, col, k


def build_logo(
    height: float,
    *,
    name: str = "LogoN",
    material: bpy.types.Material | None = None,
    location=(0.0, 0.0, 0.0),
    collection: bpy.types.Collection | None = None,
) -> bpy.types.Object:
    """The 3D "N" band; its front silhouette matches logo.png."""
    d = logo_data()
    pts, col, k = logo_points(height, d)
    normals = np.tile([0.0, -1.0, 0.0], (len(pts), 1))
    ob = build(
        pts,
        d["breite_px"] * k,
        d["dicke_px"] * k,
        name=name,
        material=material,
        tilt=col["tilt"],
        radius=col["radius"],
        normals=normals,
        u=col["u"],
        collection=collection,
    )
    ob.location = location
    ob["logo_hoehe"] = height
    return ob
